### ISSUE TITLE
Visual improvements

### ISSUE THREAD

**Issue by vokiel** [ckeditor/editor-recommendations#24]
Couple of propositions:
- [x] Change header (callout) into jumbotron version (full width background as under header and footer)
- [x] Increase line-height
- [x] Add sticky footer
