### ISSUE TITLE
Fix style issues with headers

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#35]
As @fredck pointed in [his comment](https://github.com/ckeditor/editor-recommendations/issues/32#issuecomment-188800490) to #32, we don't have consistent style for headers.

Headers should be corrected in:
- [x] Usability feature template
- [x] Use-case template
- [x] Existing usability drafts

---

All headers should conform to following convention:

```
Simple Header to Show the Convention
```
